<?php

namespace Prototype\ConfigBundle\Repository;

/**
 * ResetPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResetPasswordRepository extends \Doctrine\ORM\EntityRepository
{
}
